name: lease_recipes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-recipes:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/common-setup

    - name: Copy script to Holon
      run: cp scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp scripts/lease_recipes.txt /home/runner/work/niovad/niovad/build_dir/

    - name: Exec Lease recipes
      run: |
           set -e
           cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon' \
                             '/home/runner/work/niovad/niovad/build_dir' \
                             '/home/runner/work/niovad/niovad/holon_log' \
                              5 \
                             '/home/runner/work/niovad/niovad/build_dir/lease_recipes.txt' \
                             'lease' \
                             '/home/runner/work/go/go/bin'

    - uses: ./.github/actions/teardown-success
      if: ${{ success() }}

    - uses: ./.github/actions/teardown-failure
      if: failure() # run teardown regardless of failure
