name: bulk_recovery_recipes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/common-setup

    - name: Copy script to run recipes
      run: cp scripts/run-recipes.sh /home/runner/work/niovad/niovad/build_dir/ &&
           cp scripts/bulk_recovery_recipes.txt /home/runner/work/niovad/niovad/build_dir/

    - name: Create ssh key
      run: >
           ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa

    - name: Add key to auth file
      run: >
           cat ~/.ssh/id_rsa.pub | tee -a ~/.ssh/authorized_keys

    - name: Allow localhost authentication
      run: >
           echo "NoHostAuthenticationForLocalhost yes" > ~/.ssh/config

    - name: Ensure the owner of the key is correct
      run: |
           chmod 600 ~/.ssh/authorized_keys
           chmod 700 ~/.ssh
           sudo chmod -c 0755 ~/
           ls -la ~/.ssh

    - name: Add localhost host key to known_hosts
      run: |
           ssh-keyscan -H localhost >> ~/.ssh/known_hosts
           ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts
           chmod 644 ~/.ssh/known_hosts

    - name: Test SSH connection to localhost
      run: >
           ssh -vvv -i ~/.ssh/id_rsa -o BatchMode=yes -o StrictHostKeyChecking=no $(whoami)@localhost

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
  
    - name: deebugger for bulk recovery
      uses: csexton/debugger-action@master

    - name:  run recipes
      run: cd /home/runner/work/niovad/niovad/build_dir/holon/ &&
           ../run-recipes.sh '/home/runner/work/niovad/niovad/build_dir/holon'
                             '/home/runner/work/niovad/niovad/build_dir'
                             '/home/runner/work/niovad/niovad/holon_log' 5
                             '/home/runner/work/niovad/niovad/build_dir/bulk_recovery_recipes.txt'
                             'pumicedb'
                             '/home/runner/work/go/go/bin'

    - uses: ./.github/actions/teardown-success
      if: ${{ success() }}

    - uses: ./.github/actions/teardown-failure
      if: failure() # run teardown regardless of failure
